import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "API - LOGIN",
  description: 'Generated by Next.js',
  keywords: 'API, Next.js, Login, Logout, Authentication',
  authors: {
    name: 'Edinson Madrid'
  },
  icons:{
    icon: '/favicon.ico',
  }
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang='es'>
			<body className={inter.className}>{children}</body>
		</html>
  );
}
